### ISSUE TITLE
Drunk players... get a -10% damage TAKEN bonus? Is that right?

### ISSUE THREAD

**Issue by Synival** [Synival/BaseMUD#83]

**Comment by rhoxie21** [comment]
@Synival - I am unsure this is case if we are looking at the same thing in fight.c

    /* Damage modifiers. */
    if (dam > 1 && IS_DRUNK (victim))
        dam = 9 * dam / 10;

**Comment by Synival** [comment]
@rhoxie21 It looks like I meant to type 10%, not 0%. Whoops. Still - looking at the original ROM code, it looks like being drunk is a straight-up -10% damage taken bonus buff. Is this how it's supposed to work?

**Comment by stevepaul1982** [comment]
The original intent was a 10% damage reduction from being drunken yes - which is then off-set by Drunken status reducing skill %s - not sure if that is also in place in the stock.

Examples of where this have been used in ROM muds are to give damage reduction to everybody when drunk, with skill reductions - then have specific circumstances where the negatives are removed.  The classic example i've seen is Dwarves not getting negatives from being drunk - allowing them to them use Alcohol as a 'buff' and getting damage reduction to make them more tanky.

**Comment by Synival** [comment]
@stevepaul1982 Okay, that makes sense, thanks. Yes, the skill % penalty is also in stock. This is intended behavior, so Ill close the issue :)
